
console.log("In Built Object ____________________ ") ; 

// PI ...
console.log(Math.PI) ;

// MAX .... / MIN  ......
console.log( " the min is : " , Math.max(12, 786 , 754, 112, 13, 3, 4,355, 6, 454 )) ; 
console.log( " the min is : " , Math.min(12, 786 , 754, 112, 13, 3, 4,355, 6, 454 )) ; 

// max 
// min 
// power 
// random 
// pi 
// --- etc ---

// ---- date ----------------
let date = new Date() ; 
console.log(date) ; 
